### ISSUE TITLE
Models implementation: number of channels

### ISSUE THREAD

**Issue by antheva** [DefangChen/SimKD#11]
Hi, thank you for releasing the code.

I noticed that almost all models have a (much) smaller number of channels with respect to the default ones, e.g. wrt the torchvision implementation ones. Is there a reason for this design choice? 
Thank you.

**Comment by DefangChen** [comment]
Do you mean the default implementation in https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py ?
Actually, the torchvision implementation is designed for ImageNet dataset.
We follow the original implementation of ResNet paper and previous compared knowledge distillation methods to adopt different architectures for CIFAR and ImageNet.

**Comment by antheva** [comment]
Which KD method repository / implementation are you referring to exactly? I knew that the first layers of ResNet need to be changed for CIFAR100 but I didn't know the number of channels require an adjustment as well.

**Comment by DefangChen** [comment]
A typical implementation can be found at https://github.com/HobbitLong/RepDistiller.
In addition to the first layer, ResNet's default setting for CIFAR-100 changes the channel numbers based on Kaiming's cvpr paper.
I guess If you use the ImageNet architecture, it should also work fine. Keep in mind that we heavily use the Wide ResNet architecture to increase the channel numbers, such as ResNet-32x4.

**Comment by antheva** [comment]
Thank you for your quick and clear answers.
Just one more question: why didn't you extensively evaluate your method on ImageNet too? If I'm not wrong there's only a couple of experiments in the paper and supplementary materials.

**Comment by DefangChen** [comment]
The reason is simply the lack of adequate computational resources. At that time, I only have access to 4xA40 for a limited period of time. However, I strongly believe that thoroughly evaluating existing methods (reproducing and tuning them) on ImageNet is very valuable and can potentially lead to promising research ideas.

**Comment by antheva** [comment]
Thanks!
