### ISSUE TITLE
Other student models

### ISSUE THREAD

**Issue by Leila-Malihi** [DefangChen/SimKD#13]
Hi,
Could you please tell me, for what kind of student model I can use this code? I tried to use for example resnet 20, vgg-8 also but there was an error:
UnboundLocalError: local variable 'model_s' referenced before assignment

**Comment by DefangChen** [comment]
Please refer to https://github.com/DefangChen/SimKD/blob/main/models/__init__.py

**Comment by Leila-Malihi** [comment]
Thanks for answering, also could you please tell me the teacher I can used is just what you refer to:
https://drive.google.com/drive/folders/1j7b8TmftKIRC7ChUwAqVWPIocSiacvP4

or I can use other teachers as well?

-------- Original Message --------
Subject: Re: [DefangChen/SimKD] Other student models (Issue #13)
Date: Thursday, June 01, 2023 17:03 CEST
From: DefangChen ***@***.***>
Reply-To: DefangChen/SimKD ***@***.***>

To: DefangChen/SimKD ***@***.***>
CC: Leila-Malihi ***@***.***>, Author ***@***.***>

References: 




 
 
Please refer to https://github.com/DefangChen/SimKD/blob/main/models/__init__.py

**Comment by DefangChen** [comment]
Of course you can use other teachers. You may need to modify https://github.com/DefangChen/SimKD/blob/main/models/__init__.py to include the new models.

**Comment by Leila-Malihi** [comment]
thanks alot for your answering.

-------- Original Message --------
Subject: Re: [DefangChen/SimKD] Other student models (Issue #13)
Date: Thursday, June 01, 2023 18:23 CEST
From: DefangChen ***@***.***>
Reply-To: DefangChen/SimKD ***@***.***>

To: DefangChen/SimKD ***@***.***>
CC: Leila-Malihi ***@***.***>, Author ***@***.***>

References: 




 
 
Of course you can use other teachers. You may need to modify https://github.com/DefangChen/SimKD/blob/main/models/__init__.py to include the new models.

**Comment by Leila-Malihi** [comment]
Could you please tell me the other pre-trained models on Cifar100 for classification task, from where can I download them?

-------- Original Message --------
Subject: Re: [DefangChen/SimKD] Other student models (Issue #13)
Date: Thursday, June 01, 2023 18:23 CEST
From: DefangChen ***@***.***>
Reply-To: DefangChen/SimKD ***@***.***>

To: DefangChen/SimKD ***@***.***>
CC: Leila-Malihi ***@***.***>, Author ***@***.***>

References: 




 
 
Of course you can use other teachers. You may need to modify https://github.com/DefangChen/SimKD/blob/main/models/__init__.py to include the new models.

**Comment by Leila-Malihi** [comment]
Is it possible to tell me, the models you uploaded in google drive all are pre-trained on CifaR -100?

-------- Original Message --------
Subject: Re: [DefangChen/SimKD] Other student models (Issue #13)
Date: Thursday, June 01, 2023 18:23 CEST
From: DefangChen ***@***.***>
Reply-To: DefangChen/SimKD ***@***.***>

To: DefangChen/SimKD ***@***.***>
CC: Leila-Malihi ***@***.***>, Author ***@***.***>

References: 




 
 
Of course you can use other teachers. You may need to modify https://github.com/DefangChen/SimKD/blob/main/models/__init__.py to include the new models.

**Comment by DefangChen** [comment]
Apart from ResNet50, others are for CIFAR-100.

**Comment by Leila-Malihi** [comment]
Dear Defangchen,
Do you have the distilled student ? I want to cite them.

Best Regards,
Leila

On Wednesday, June 07, 2023 15:10 CEST, DefangChen ***@***.***> wrote:
 
 
Closed #13 as completed.

**Comment by Leila-Malihi** [comment]
Hi,
From the distillation method there is 'hint' and 'attention' what are they?
Also for 'AT' and Fitnet they are not in the choices. How can I add them

 parser.add_argument('--distill', type=str, default='kd', choices=['kd', 'hint', 'attention', 'similarity', 'vid',
                                                                      'crd', 'semckd','srrl', 'simkd'])

Thank you

On Wednesday, June 07, 2023 15:10 CEST, DefangChen ***@***.***> wrote:
 
 
Closed #13 as completed.

**Comment by Leila-Malihi** [comment]
Hello,
Sorry I asked alot, I  am so thankful if you answer them. I distilled knowledge to resnet 8*4 with KD method, the output is like that, but in your paper said the accuracy should be 78 here is 1
