### ISSUE TITLE
请问该方法可以应用于目标检测领域吗

### ISSUE THREAD

**Issue by DonMuv** [DefangChen/SimKD#3]
Hello
我想问一下SimKD可以应用MaskRCNN等目标检测任务中吗

**Comment by DefangChen** [comment]
Of course. The basic idea of SimKD is reusing the pre-trained high-level parameters while re-parameterizing the low-level ones with fewer parameters. This technique may be potentially used in arbitrary supervised learning tasks, such as semantic segmentation, object detection. 
You can try it out for yourself.

**Comment by DonMuv** [comment]
Thanks!
