### ISSUE TITLE
DDP for teacher

### ISSUE THREAD

**Issue by trinhvg** [DefangChen/SimKD#6]
Hi, I run your code and encounter the error bellow when I run the code for 'semckd' (I havent try the SimKD). I think because we don't directly use the parameter in teacher. Please give some advice if possible. Thank you!

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 4 5 6 7 12 13 14 15 20 21 22 23 28 29 30 31 36 37 38 39 44 45 46 47 52 53 54 55 60 61 62 63
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

**Comment by DefangChen** [comment]
I guess this error is caused by library version mismatch (e.g., PyTorch) since I don't encounter this one in my environment.

**Comment by trinhvg** [comment]
I use pytorch 1.11.0 and torch.cuda.nccl.version()=21.0.3. For now I dont put teacher on DDP, I will install new environment later and update in here if it helps. Thank you!
